"""001_initial_schema

Revision ID: 491a07bb915f
Revises: 
Create Date: 2025-12-23 16:14:25.022703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491a07bb915f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('process_number', sa.String(), nullable=True),
    sa.Column('court', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('share_token', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('share_expires_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('share_access_level', sa.String(), server_default='view', nullable=False))
    op.create_index(op.f('ix_documents_share_token'), 'documents', ['share_token'], unique=True)
    op.add_column('library_items', sa.Column('token_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_items', 'token_count')
    op.drop_index(op.f('ix_documents_share_token'), table_name='documents')
    op.drop_column('documents', 'share_access_level')
    op.drop_column('documents', 'share_expires_at')
    op.drop_column('documents', 'share_token')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
