"""restore_missing_columns

Revision ID: ef2c21b089eb
Revises: 2c0b1c4a8b3d
Create Date: 2026-01-14 22:04:47.104208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2c21b089eb'
down_revision: Union[str, None] = '2c0b1c4a8b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('share_token', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('share_expires_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('share_access_level', sa.String(), nullable=False))
    op.create_index(op.f('ix_documents_share_token'), 'documents', ['share_token'], unique=True)
    op.add_column('library_items', sa.Column('token_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_items', 'token_count')
    op.drop_index(op.f('ix_documents_share_token'), table_name='documents')
    op.drop_column('documents', 'share_access_level')
    op.drop_column('documents', 'share_expires_at')
    op.drop_column('documents', 'share_token')
    # ### end Alembic commands ###
